### ISSUE TITLE
i cannot rotation the map 

### ISSUE THREAD

**Issue by LaplaceTor** [oqyh/cs2-Game-Manager#3]
This is my vonfig
```
//-----------------------------------------------------------------------------------------

  //Restart The Server If (RestartWhenXPlayersInServerORLess) After (RestartXTimerInMins)
  //RestartServerMode (1) = Restart Method
  //RestartServerMode (2) = Crash Method Sometimes Restart Will Not Work Use This Method Instead
  "RestartServerMode": 2,
  "RestartXTimerInMins": 90,
  "RestartWhenXPlayersInServerORLess": 64,
  
//-----------------------------------------------------------------------------------------

  //Rotate Maps Server If (RotationWhenXPlayersInServerORLess) After (RotationXTimerInMins)
  //RotationServerMode (1) = Get Maps From Top To Bottom In RotationServerMapList.txt
  //RotationServerMode (2) = Get Random Maps In RotationServerMapList.txt
  "RotationServerMode": 2,
  "RotationXTimerInMins": 30,
  "RotationWhenXPlayersInServerORLess": 64,
```
and in maplist.txt is 
```
ds:surf_beginner
ds:surf_mads
ds:surf_kitsune
ds:surf_deathstar
ds:surf_ace
ds:surf_rgb
ds:surf_benevolent
ds:surf_momentum
ds:surf_glass9
ds:surf_hyzer
ds:surf_ing
ds:surf_lockdown
ds:surf_mellow
ds:surf_saturday
ds:surf_teho_v1
ds:surf_nyx
ds:surf_atrium
ds:surf_tranquil
```

**Comment by oqyh** [comment]
can i see your server console 
```
ds_workshop_listmaps
```

and paste it here

**Comment by LaplaceTor** [comment]
> can i see your server console
> 
> ```
> ds_workshop_listmaps
> ```
> 
> and paste it here

`ds_workshop_listmaps
surf_beginner
surf_mads
surf_kitsune
surf_deathstar
surf_ace
surf_rgb
surf_benevolent
surf_momentum
surf_glass9
surf_hyzer
surf_ing
surf_lockdown
surf_mellow
surf_saturday
surf_teho_v1
surf_nyx
surf_atrium
surf_tranquil`

**Comment by oqyh** [comment]
what is value of
```
sv_hibernate_when_empty 
```

**Comment by LaplaceTor** [comment]
> what is value of
> ```
> sv_hibernate_when_empty 
> ```
> 

Alright, it was 1 I would try force it to 0 and test it again

**Comment by oqyh** [comment]
> This is my vonfig
> 
> ```
> //-----------------------------------------------------------------------------------------
> 
>   //Restart The Server If (RestartWhenXPlayersInServerORLess) After (RestartXTimerInMins)
>   //RestartServerMode (1) = Restart Method
>   //RestartServerMode (2) = Crash Method Sometimes Restart Will Not Work Use This Method Instead
>   "RestartServerMode": 2,
>   "RestartXTimerInMins": 90,
>   "RestartWhenXPlayersInServerORLess": 64,
>   
> //-----------------------------------------------------------------------------------------
> 
>   //Rotate Maps Server If (RotationWhenXPlayersInServerORLess) After (RotationXTimerInMins)
>   //RotationServerMode (1) = Get Maps From Top To Bottom In RotationServerMapList.txt
>   //RotationServerMode (2) = Get Random Maps In RotationServerMapList.txt
>   "RotationServerMode": 2,
>   "RotationXTimerInMins": 30,
>   "RotationWhenXPlayersInServerORLess": 64,
> ```
> 
> and in maplist.txt is
> 
> ```
> ds:surf_beginner
> ds:surf_mads
> ds:surf_kitsune
> ds:surf_deathstar
> ds:surf_ace
> ds:surf_rgb
> ds:surf_benevolent
> ds:surf_momentum
> ds:surf_glass9
> ds:surf_hyzer
> ds:surf_ing
> ds:surf_lockdown
> ds:surf_mellow
> ds:surf_saturday
> ds:surf_teho_v1
> ds:surf_nyx
> ds:surf_atrium
> ds:surf_tranquil
> ```



> > what is value of
> > ```
> > sv_hibernate_when_empty 
> > ```
> 
> Alright, it was 1 I would try force it to 0 and test it again

and make sure file name is  RotationServerMapList.txt not maplist.txt
and must be inside Game_Manager folder

```
../csgo/addons/counterstrikesharp/plugins/Game_Manager/
```

**Comment by LaplaceTor** [comment]
> > This is my vonfig
> > 
> > ```
> > //-----------------------------------------------------------------------------------------
> > 
> >   //Restart The Server If (RestartWhenXPlayersInServerORLess) After (RestartXTimerInMins)
> >   //RestartServerMode (1) = Restart Method
> >   //RestartServerMode (2) = Crash Method Sometimes Restart Will Not Work Use This Method Instead
> >   "RestartServerMode": 2,
> >   "RestartXTimerInMins": 90,
> >   "RestartWhenXPlayersInServerORLess": 64,
> >   
> > //-----------------------------------------------------------------------------------------
> > 
> >   //Rotate Maps Server If (RotationWhenXPlayersInServerORLess) After (RotationXTimerInMins)
> >   //RotationServerMode (1) = Get Maps From Top To Bottom In RotationServerMapList.txt
> >   //RotationServerMode (2) = Get Random Maps In RotationServerMapList.txt
> >   "RotationServerMode": 2,
> >   "RotationXTimerInMins": 30,
> >   "RotationWhenXPlayersInServerORLess": 64,
> > ```
> > 
> > and in maplist.txt is
> > 
> > ```
> > ds:surf_beginner
> > ds:surf_mads
> > ds:surf_kitsune
> > ds:surf_deathstar
> > ds:surf_ace
> > ds:surf_rgb
> > ds:surf_benevolent
> > ds:surf_momentum
> > ds:surf_glass9
> > ds:surf_hyzer
> > ds:surf_ing
> > ds:surf_lockdown
> > ds:surf_mellow
> > ds:surf_saturday
> > ds:surf_teho_v1
> > ds:surf_nyx
> > ds:surf_atrium
> > ds:surf_tranquil
> > ```
> 
> 
> 
> > > what is value of
> > > ```
> > > sv_hibernate_when_empty 
> > > ```
> > 
> > Alright, it was 1 I would try force it to 0 and test it again
> 
> and make sure file name is  RotationServerMapList.txt not maplist.txt
> and must be inside Game_Manager folder
> 
> ```
> ../csgo/addons/counterstrikesharp/plugins/Game_Manager/
> ```

Others config is ok (including restart)so I'm here
By the way, the force cheats 0 feature is not so useful that some maps force it to 1....is there a hook way to check if it's 1 now in css?

**Comment by oqyh** [comment]
will fix that 
but how was rotation fixed?

**Comment by LaplaceTor** [comment]
> will fix that 
> but how was rotation fixed?

Actually I have the config sv_hibernate_when_empty 0 in the boot script so there's something force it to 1 i think

**Comment by LaplaceTor** [comment]
And in my config, it should be auto change map no matter how many people in my server ( the players limit of my server is 10)
auto restart is ok so i don't know why auti change map is not work

**Comment by oqyh** [comment]
message me in discord

oqyh

**Comment by LaplaceTor** [comment]
> message me in discord
> 
> oqyh
> 

My name is NVGoonaGUP

**Comment by oqyh** [comment]
works
