### ISSUE TITLE
Logging in for observers

### ISSUE THREAD

**Issue by AlMinoOj** [oqyh/cs2-Game-Manager#4]
When the player dies, it throws it to the observers for a second and then back, while losing money.
![image](https://github.com/oqyh/cs2-Game-Manager/assets/128634781/eebef637-641c-4290-8e93-ba7c913dd2f4)
![image](https://github.com/oqyh/cs2-Game-Manager/assets/128634781/6823da82-3a0d-4e8f-8011-02b6598aa9b9)

**Comment by oqyh** [comment]
> When the player dies, it throws it to the observers for a second and then back, while losing money. ![image](https://private-user-images.githubusercontent.com/128634781/307593418-eebef637-641c-4290-8e93-ba7c913dd2f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDg2NTIsIm5iZiI6MTcwOTQ0ODM1MiwicGF0aCI6Ii8xMjg2MzQ3ODEvMzA3NTkzNDE4LWVlYmVmNjM3LTY0MWMtNDI5MC04ZTkzLWJhN2M5MTNkZDJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QwNjQ1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGRmM2EwYzQ3ODVlMmU1MDEyNjVmZmZkOGZkY2JlYTNlODI4ZmVjZWNiYjg1ZTUxYzRiZmEwMGEzY2VmNTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D1ra4H7ZT1dgMb4jhZaIjQiiLO98n7iMl-T0gEGrQHI) ![image](https://private-user-images.githubusercontent.com/128634781/307593449-6823da82-3a0d-4e8f-8011-02b6598aa9b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDg2NTIsIm5iZiI6MTcwOTQ0ODM1MiwicGF0aCI6Ii8xMjg2MzQ3ODEvMzA3NTkzNDQ5LTY4MjNkYTgyLTNhMGQtNGU4Zi04MDExLTAyYjY1OThhYTliOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QwNjQ1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjUxZDkxZTE3MDZlNGZkNjE1ZjQ5N2ZjYmZkYmRmMmVlMjYxYjRjNzE4OTg1ZThlOWFkZWVhYjViODM2NzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jfzdM_VbE4qNJetGZoBk1Dokzv7dU8-uUECz4UwVen4)

this build for surf / kz / death any game that has no competitive mode i don't recommend to use remove body on competitive mode
